services:
  frontend-bucket-manager:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
    container_name: frontend-bucket-manager
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - shared
    depends_on:
      - api-bucket-manager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3-manager.rule=Host(`s3-manager.localhost`)"
      - "traefik.http.services.s3-manager.loadbalancer.server.port=80"

  api-bucket-manager:
    build: ./backend
    container_name: api-bucket-manager
    ports:
      - "3001:3001"
    environment:
      # AWS credentials via IAM role (recommended for EC2)
      - REGION=${REGION:-eu-central-1}
      - BUCKET_NAME=${BUCKET_NAME}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
      # Only use these if IAM role is not available
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
    restart: unless-stopped
    networks:
      - shared

networks:
 shared:
    driver: bridge

